# Generated by Django 3.2.4 on 2021-06-23 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndigoGamesStudio', '0002_alter_gamepost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepost',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
