# Generated by Django 3.2.4 on 2021-06-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndigoGamesStudio', '0005_remove_gamepost_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamepost',
            name='icon',
            field=models.CharField(choices=[('icon-android', 'icon-android'), ('icon-windows', 'icon-windows')], default='icon-android', max_length=20),
        ),
    ]
