# Generated by Django 3.2.4 on 2021-07-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndigoGamesStudio', '0006_gamepost_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('Programmer', 'Programmer'), ('Graphics Designer', 'Graphics Designer')], default='Programmer', max_length=50)),
                ('social_icon_first', models.CharField(choices=[('icon-linkedin-squared', 'icon-linkedin-squared'), ('icon-github-circled-alt2', 'icon-github-circled-alt2'), ('https://img.icons8.com/ios/50/000000/sketchfab.png', 'https://img.icons8.com/ios/50/000000/sketchfab.png')], default='icon-linkedin-squared', max_length=255)),
                ('social_icon_second', models.CharField(choices=[('icon-linkedin-squared', 'icon-linkedin-squared'), ('icon-github-circled-alt2', 'icon-github-circled-alt2'), ('https://img.icons8.com/ios/50/000000/sketchfab.png', 'https://img.icons8.com/ios/50/000000/sketchfab.png')], default='icon-linkedin-squared', max_length=255)),
                ('person_img', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
