# Generated by Django 3.2.4 on 2021-07-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IndigoGamesStudio', '0008_auto_20210714_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutU',
            new_name='AboutUs',
        ),
    ]
