# Generated by Django 3.2.4 on 2021-07-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndigoGamesStudio', '0009_rename_aboutu_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_email', models.CharField(max_length=30)),
                ('social_media_first', models.CharField(choices=[('icon-instagram', 'icon-instagram'), ('icon-facebook-squared', 'icon-facebook-squared')], default='icon-instagram', max_length=40)),
                ('social_media_second', models.CharField(choices=[('icon-instagram', 'icon-instagram'), ('icon-facebook-squared', 'icon-facebook-squared')], default='icon-facebook-squared', max_length=40)),
            ],
        ),
    ]
