# Generated by Django 3.2.4 on 2021-08-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndigoGamesStudio', '0013_auto_20210731_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='test',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='social_icon_third',
            field=models.CharField(blank=True, choices=[('icon-linkedin-squared', 'icon-linkedin-squared'), ('icon-github-circled-alt2', 'icon-github-circled-alt2'), ('https://img.icons8.com/ios/50/000000/sketchfab.png', 'https://img.icons8.com/ios/50/000000/sketchfab.png')], max_length=255, null=True),
        ),
    ]
