# Generated by Django 3.2.4 on 2021-08-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndigoGamesStudio', '0014_auto_20210801_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='test',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='social_icon_first_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
