# Generated by Django 3.2.4 on 2021-08-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndigoGamesStudio', '0015_auto_20210801_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='social_icon_second_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='social_icon_third_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='social_media_first_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='social_media_second_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
