# Generated by Django 3.2.4 on 2021-08-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IndigoGamesStudio', '0017_auto_20210802_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='social_icon_fourth',
            field=models.CharField(blank=True, choices=[('icon-linkedin-squared', 'icon-linkedin-squared'), ('icon-github-circled-alt2', 'icon-github-circled-alt2'), ('https://img.icons8.com/ios/50/000000/sketchfab.png', 'https://img.icons8.com/ios/50/000000/sketchfab.png')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='social_icon_third_fourth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
